### ISSUE TITLE
 different # of slices in volume

### ISSUE THREAD

**Issue by sepidhk** [ZFTurbo/segmentation_models_3D#13]
Is it necessary for volumes to be in the same size. Is it possible to use these models for a datasets that volumes have different number of slices? I am working on a 3d liver volume segmentation and my volumes have fixed width and heights but different number of slices in z axis. for example first volume is in shape 512, 512, 26 and the second one is 512, 512, 32. So, my question is, should I fixed the number of slices for the third dimension for the input_shape?

**Comment by ZFTurbo** [comment]
Yes, you need to make everything of one size. You use maximum, let's say (512, 512, 32) and then if number of slices is lower - fill it with zeros. If higher than cut what's not fit. Or you can try Resize from volumentations.

**Comment by sepidhk** [comment]
Thanks for the quick reply and amazing library.
