### ISSUE TITLE
how does the 3d cnn pretrained on ImageNet?

### ISSUE THREAD

**Issue by jizhang02** [ZFTurbo/segmentation_models_3D#22]
Hello,

As we know that many 2d CNN architectures have pretrained weights thanks to ImageNet or other huge datasets.

I just wonder does the 3d CNN architecture's backbone in this repo have pretrained weights? If it does, how it comes?

Thank you in advance!

Jing

**Comment by ZFTurbo** [comment]
Hello, you can read the idea in this paper:
https://arxiv.org/pdf/2104.01687.pdf

In short I converted 2D imagenet weights in 3D variant.
