### ISSUE TITLE
efficientnetb3 cannot run

### ISSUE THREAD

**Issue by faheem-khaskheli** [ZFTurbo/segmentation_models_3D#3]
i tried using efficientnetb3 with unet, it was created but when i try to either fit or predict, it just do not response and code stop there without doing anything at all.

i am using NVIDIA RTX 3070 8G GPU

**Comment by ZFTurbo** [comment]
I believe it's because DepthwiseConv3D is not exists in TensorFlow. So for EffNet3D I used some 3rd party realisation and I think it's slow down everything. We need to wait when TF team will add it or write it yourself. )
