### ISSUE TITLE
Correct Tensorflow/Keras Versions

### ISSUE THREAD

**Issue by diegoPasini** [ZFTurbo/segmentation_models_3D#30]
Hello!
Love the library, it's been super useful for a segmentation project I've been working on. I am currently trying to run the model on CUDA 12, and I saw that in the latest version, 1.0.6, you guys are able to support higher versions of tensorflow (2.13 or above). Currently, when I try to install it with pip, however, I get the following dependency error: 
segmentation-models-3d 1.0.6 requires keras==2.8.0, but you have keras 2.13.1 which is incompatible.
segmentation-models-3d 1.0.6 requires tensorflow==2.8.0, but you have tensorflow 2.13.1 which is incompatible.
![image](https://github.com/ZFTurbo/segmentation_models_3D/assets/74738050/601ce5c0-96e0-419c-9012-0883abcf3b21)
I can't downgrade my CUDA version for my GPU to make it compatible with tensorflow==2.8.0. Would it be possible to have some help?
Thank you so much!

**Comment by ZFTurbo** [comment]
Sorry I forgot to change 

```
install_requires=[
        'tensorflow==2.8.0',
        'keras==2.8.0',
        "keras_applications==1.0.8",
        "classification_models_3D==1.0.8",
    ],
```

in setup.py.

Current version of code must work with:

```
tensorflow>=2.13.0,<=2.15.0
keras==2.13.1
keras_applications==1.0.8
classification_models_3D==1.0.10
```

**Comment by diegoPasini** [comment]
Thank you!

**Comment by diegoPasini** [comment]
Works Now!
