### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by Manasa-3** [ZFTurbo/segmentation_models_3D#35]
IndexError                                Traceback (most recent call last)
[<ipython-input-30-95f29ceb0ec0>](https://localhost:8080/#) in <cell line: 65>()
     63 
     64 # Initialize Model, Loss Function, and Optimizer
---> 65 model = smp.Unet(
     66     'resnet34',
     67     encoder_weights=None,

7 frames
[/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py](https://localhost:8080/#) in build(self, input_shape)
    168 
    169     def build(self, input_shape):
--> 170         shape = (input_shape[self.axis],)
    171         if self.scale:
    172             self.gamma = self.add_weight(

IndexError: tuple index out of range.                                                                                                                                                                   Please help me out for this error, My image is of shape (256,128,128)

**Comment by ZFTurbo** [comment]
Can you post your code at line 65 and a bit after?

**Comment by Manasa-3** [comment]
train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True, collate_fn=custom_collate_fn, pin_memory=True)
print(f"Number of workers: {train_loader.num_workers}")
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False, collate_fn=custom_collate_fn, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=2, shuffle=False, collate_fn=custom_collate_fn, pin_memory=True)

# Initialize Model, Loss Function, and Optimizer
model = smp.Unet(
    'resnet34',
    encoder_weights=None,
    input_shape=image.shape
)

criterion = nn.MSELoss()
optimizer = Adam(model.parameters(), lr=0.001)

num_epochs = 10  # Define the number of epochs

print(f"Initial GPU memory allocated: {torch.cuda.memory_allocated()} bytes")
# Training loop
scaler = GradScaler()
for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    running_loss = 0.0
    for batch_idx, (images, masks) in enumerate(train_loader):
        images, masks = images.to(device), masks.to(device)
        images = images.unsqueeze(0)  # This line seems unnecessary unless you're intentionally adding an extra dimension for some reason
        optimizer.zero_grad()
        # print(torch.cuda.memory_summary(device=None, abbreviated=False))

        # Use autocast to enable mixed precision
        with autocast():
            outputs = model(images)
            loss = criterion(outputs, masks)

        # Scale the loss and call backward
        scaler.scale(loss).backward()

        # Unscales the gradients and calls optimizer.step
        scaler.step(optimizer)

        # Updates the scale for next iteration
        scaler.update()

        running_loss += loss.item()
        if True:  # Always true, so this block runs for every batch
          print(f"Epoch [{epoch+1}/{num_epochs}], Batch [{batch_idx+1}/{len(train_loader)}], Loss: {running_loss/(batch_idx+1):.4f}")
          running_loss = 0.0
          gc.collect()
This is the code from line 65...

**Comment by ZFTurbo** [comment]
What's value of `image.shape`?

**Comment by Manasa-3** [comment]
okay thankyou, I'll check it out.
